---
title: "First Year Exam"
author: "Diana Ofelia Lopez Cantu A59019192"
format: html
---

First, libraries need to be called:

```{r}
library(lubridate)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(scales)
```

```{r}
covid <- read.csv("/Users/dianalopezcantu/Desktop/covid19_variants.csv")
#covid
```

```{r}
covid$date <- ymd(covid$date)
df <- data.frame(covid$date, covid$variant_name, covid$percentage)
df2 <- dplyr::filter(df, 
                     covid$variant_name 
%in% c("Alpha", "Beta", "Delta", "Epsilon", "Gamma","Lambda", "Omicron","Mu"))
df3 <- subset(df2, covid$date < "2022-01-01")
#df3
```

```{r}
#Create a plot

ggplot(df3) + aes(x = covid.date, y = covid.percentage) + 
  theme_bw() +
  geom_line(aes(colour =covid.variant_name)) + 
  xlab("") + ylab("Percentage of sequenced specimens") + 
  labs(title ="Covid-19 variants in California",
       caption = "Data Source: <https://www.cdph.ca.gov/>", colour = NULL) + 
  scale_x_date(date_labels = "%b %Y", date_breaks = "1 month") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
